### ISSUE TITLE
igcmd stop working

### ISSUE THREAD

**Issue by niresh1234** [ImageGlass/Spider#4]
igcmd stop working
sometime get this and sometime not

![Screenshot (289)](https://user-images.githubusercontent.com/98110551/172033075-ca78728f-1d63-4346-8243-d19c1179ffe7.png)

### Video
https://user-images.githubusercontent.com/3154213/172355167-2c00b4ad-0dea-4fd0-93f3-463d1480512e.mp4

**Comment by d2phap** [comment]
Hi @niresh1234 
`igcmd.exe` is a utility that helps for running these commands: https://imageglass.org/docs/command-line-utilities

<html>
<body>


Function | Command
-- | --
Set desktop wallpaper | `igcmd.exe setwallpaper <string imgPath> [int style]`
Display Check for update dialog | `igcmd.exe igupdate`
Check for update without GUI | `igcmd.exe igautoupdate`
Display First-launch configurations dialog | `igcmd.exe firstlaunch`


</body>
</html>

Only `igautoupdate` command auto-runs every 5 days to check for the new update.
You can temporarily rename this file from `igcmd.exe` to `igcmd_.exe` to see if the issue still persists. It's located in the installed folder of ImageGlass Spider.

If possible, you can provide the steps to lead to this error. It will help a lot for debugging.
Thanks

**Comment by niresh1234** [comment]
One Main Thing, That I Notice

- When I Disconect My PC from Internet, Get This Issue (Spider as well as Kobe)

- **For Testing, Try Some Thing on Previous Version (8.5.1.22), Not Get Any Such Issue**

**Comment by niresh1234** [comment]
Watch this youtube video **[(Screen Recording](https://www.youtube.com/watch?v=e0RUhWFAXks))**

https://www.youtube.com/watch?v=e0RUhWFAXks

**Comment by d2phap** [comment]
Thanks @niresh1234 
I will check it and get back to you here.

**Comment by niresh1234** [comment]
OK, Have a nice day..

**Comment by d2phap** [comment]
Hi @niresh1234 

A few more tries,

#### 1. Can you help me to click on Menu > Help > Check for update...?
It should show the Check for update dialog.

![image](https://user-images.githubusercontent.com/3154213/172355880-61c699b3-4acd-434d-b9c0-67753a507012.png)


#### 2. Run this command in the ImageGlass folder:
```
igcmd.exe igautoupdate
```
It should not show any thing.

![image](https://user-images.githubusercontent.com/3154213/172356654-c2bb32b9-0714-49e3-b2b0-4078c1831ff4.png)

**Comment by niresh1234** [comment]
_**OK, All The Best!**_

**Comment by d2phap** [comment]
@niresh1234 
Can you help me test this build: [ImageGlass_Spider_8.6.6.6_x64.zip](https://github.com/ImageGlass/Spider/files/8866897/ImageGlass_Spider_8.6.6.6_x64.zip)

Just extract and copy all files to the installed folder of ImageGlass, or extract anywhere and run.

**Comment by niresh1234** [comment]
Same (Not any difference)
https://www.youtube.com/watch?v=wkkg3usX6ak

[![Alt text](https://img.youtube.com/vi/wkkg3usX6ak/0.jpg)](https://www.youtube.com/watch?v=wkkg3usX6ak)

**Comment by d2phap** [comment]
It seems you're not using the the zip file here: https://github.com/ImageGlass/Spider/issues/4#issuecomment-1150663015
I can see the "Date modified" and "Size" are different. Can you help to check and confirm again?


![image](https://user-images.githubusercontent.com/3154213/172989820-bfcbc40a-415a-418c-99e6-b5fcb748effc.png)

**Comment by niresh1234** [comment]
Oh, I See Only Filename and I thought, The File Some as (8.6.6.6 Main Release Build)..

I Will Test This File (Menson in the https://github.com/ImageGlass/Spider/issues/4#issuecomment-1150663015) and then Replying soon

**Comment by d2phap** [comment]
That's great!
Thanks for helping me. I will prepare an update

**Comment by niresh1234** [comment]
Thanks For Quick Replay
As well as Take Action on This https://github.com/d2phap/ImageGlass/issues/1352

**Comment by niresh1234** [comment]
Have A Good Day!

**Comment by d2phap** [comment]
Published new release https://github.com/ImageGlass/Spider/releases/tag/8.6.7.13
